
name: query api verification workflow
run-name: @${{ github.actor }} on @${{ github.event_name }};

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '* 12 * * 5'

jobs:
  test_query_endpoint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Dependencies setup."
        run: sudo apt install curl;
      - name: "test_query script execution."
        run: ./scripts/test_query.sh
      - name: "Success."
        run: echo Job Successful // Request passes.

